name: custom_theme
description: "Custom theme"
version: 0.0.5

environment:
  sdk: 2.14.0


dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
